package bots

import (
	"fmt"
	"strings"
	"time"
)

func GenerateDefaultTemplate(version string) string {
	b := &strings.Builder{}

	t := time.Now()

	b.WriteString("// BotProfiles - CS:Source - v" + version + "\n")
	b.WriteString("// Generated on " + t.Format("2006-01-02 15:04:05") + "\n")
	b.WriteString("// https://github.com/joshdevelopsIRL/botprofiles-cs-source\n")
	b.WriteString("// Note: This file is autogenerated without modification\n")
	b.WriteString("\n\n")
	b.WriteString("// Default Template\n")
	b.WriteString("Template Default\n")
	b.WriteString("\tSkill = 50\n")
	b.WriteString("\tAggression = 50\n")
	b.WriteString("\tReactionTime = 0.5\n")
	b.WriteString("\tAttackDelay = 0.5\n")
	b.WriteString("\tTeamwork = 50\n")
	b.WriteString("\tWeaponPreference = none\n")
	b.WriteString("\tDifficulty = NORMAL\n")
	b.WriteString("\tVoicePitch = 100\n")
	b.WriteString("\tSkin = 0\n")
	b.WriteString("End\n\n")

	return b.String()
}

func GenerateWeaponTemplates() string {
	b := &strings.Builder{}

	for affinity, weapons := range WeaponAffinities {
		b.WriteString("// " + affinity.String() + "\n")
		b.WriteString("// Uses: [" + strings.Join(weapons, ", ") + "]\n")
		b.WriteString("Template " + affinity.String() + "\n")
		for _, weapon := range weapons {
			b.WriteString("\tWeaponPreference = " + weapon + "\n")
		}
		b.WriteString("End\n\n")
	}

	return b.String()
}

func GenerateDifficultyTemplates() string {
	b := &strings.Builder{}

	for difficulty := range DefaultConfigs {
		b.WriteString("// For " + difficulty.String() + " Difficulty\n")
		b.WriteString("Template " + difficulty.TemplateName() + "\n")
		b.WriteString("\tDifficulty = " + difficulty.String() + "\n")
		b.WriteString(fmt.Sprintf("\tCost = %d\n", difficulty.Int()))
		b.WriteString("End\n\n")
	}

	return b.String()
}
